import { Printer } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useReactToPrint } from 'react-to-print';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';
import api from '../../lib/axios';

export const StudentGrades = () => {
  const [grades, setGrades] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const componentRef = useRef(null); // Reference for the printer

  useEffect(() => {
    const fetchGrades = async () => {
      try {
        const res = await api.get('/portal/grades');
        setGrades(res.data.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchGrades();
  }, []);

  // Hook for printing
  const handlePrint = useReactToPrint({
    contentRef: componentRef,
    documentTitle: 'Student Report Card',
  });

  if (loading) return <div className="p-8">Loading Grades...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold">My Academic Record</h1>
        <Button onClick={() => handlePrint()} className="gap-2 bg-blue-600 hover:bg-blue-700">
          <Printer size={16} /> Print Report Card
        </Button>
      </div>

      {/* This is the card that appears on screen */}
      <Card>
        <CardHeader><CardTitle>Report Card</CardTitle></CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Subject</TableHead>
                <TableHead>Teacher</TableHead>
                <TableHead>Term</TableHead>
                <TableHead className="text-right">Score</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {grades.length === 0 ? (
                <TableRow><TableCell colSpan={4} className="text-center">No grades posted yet.</TableCell></TableRow>
              ) : (
                grades.map((g, i) => (
                  <TableRow key={i}>
                    <TableCell>
                      <div className="font-medium">{g.subject}</div>
                      <div className="text-xs text-slate-500">{g.code}</div>
                    </TableCell>
                    <TableCell>{g.teacher}</TableCell>
                    <TableCell>{g.term}</TableCell>
                    <TableCell className="text-right font-bold text-blue-600">{g.score}</TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* === HIDDEN PRINTABLE COMPONENT === */}
      {/* This only shows up when printing */}
      <div style={{ display: 'none' }}>
        <div ref={componentRef} className="p-8 bg-white text-black">
          <div className="text-center border-b-2 border-black pb-4 mb-6">
            <h1 className="text-2xl font-bold uppercase">Official Report Card</h1>
            <p className="text-sm">School Management System • SY 2025-2026</p>
          </div>
          
          <table className="w-full border-collapse border border-black">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-black p-2 text-left">Subject</th>
                <th className="border border-black p-2 text-left">Teacher</th>
                <th className="border border-black p-2 text-center">Term</th>
                <th className="border border-black p-2 text-center">Grade</th>
              </tr>
            </thead>
            <tbody>
              {grades.map((g, i) => (
                <tr key={i}>
                  <td className="border border-black p-2">{g.subject}</td>
                  <td className="border border-black p-2">{g.teacher}</td>
                  <td className="border border-black p-2 text-center">{g.term}</td>
                  <td className="border border-black p-2 text-center font-bold">{g.score}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="mt-12 flex justify-between">
            <div className="text-center pt-8 border-t border-black w-1/3">Principal's Signature</div>
            <div className="text-center pt-8 border-t border-black w-1/3">Adviser's Signature</div>
          </div>
          <div className="text-center text-xs mt-12 text-gray-500">Generated by SMS System</div>
        </div>
      </div>

    </div>
  );
};